version: '3.7'
services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql_compose_v1
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: englishappv1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  springboot:
    build: .
    image: english-vinfast-app
    container_name: english_vinfast_app_v1
    environment:
      MYSQL_HOST: mysql_compose_v1
      MYSQL_POST: 3306
      MYSQL_DBNAME: englishappv1
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql-data:
